### ISSUE TITLE
[DEPRECATED]: ansible.builtin.include has been removed

### ISSUE THREAD

**Issue by waza-ari** [PowerDNS/pdns_recursor-ansible#153]
This role's `main.yml` file uses `ansible.builtin.include` statements, which have been [deprecated and removed](https://docs.ansible.com/ansible/5/collections/ansible/builtin/include_module.html) in version 2.16. Trying this with a recent ansible version yields

```
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
```

Simply replacing `include` with `include_tasks` works perfectly fine.

**Comment by shaunbugler** [comment]
Duplicates #152

**Comment by waza-ari** [comment]
My bad, only searched through the issues, didn't check PRs for fixes. Thanks!
