### ISSUE TITLE
[documentation] requirements.yml/install this role

### ISSUE THREAD

**Issue by strarsis** [PowerDNS/pdns_recursor-ansible#26]
I want to install this role using ansible-galaxy, I added it as source to requirements.yml:
```yml
- src: https://github.com/PowerDNS/pdns_recursor-ansible
  name: PowerDNS.pdns_recursor
````
And install it using `ansible-galaxy install -r requirements.yml`.

The role files seem to be placed indeed into a folder in vendor/roles/ - but `ansible-galaxy` fails before it can install the sub-dependency `atosatto.packages-extras`:
````
- extracting PowerDNS.pdns_recursor to [...]/project/vendor/roles/PowerDNS.pdns_recursor
 [WARNING]: - PowerDNS.pdns_recursor was NOT installed successfully: Could not update files in [...]/project/vendor/roles/PowerDNS.pdns_recursor: [Errno 95] Operation not supported
````
Is it required to specify the sub-dependency `atosatto.packages-extras` next 
to `PowerDNS.pdns_recursor`, too?

**Comment by atosatto** [comment]
Ehi @strarsis,
the correct way of adding this role as dependency is the following:

```
- src: https://github.com/PowerDNS/pdns_recursor-ansible.git
  scm: git
  version: master
  name: powerdns.pdns_recursor
```

`ansible-galaxy` will then automatically download for you the recursive dependencies.

**Comment by strarsis** [comment]
@atosatto: Thanks for the fast answer.

With the new requirements.yml config I still get an error when installing from it using `ansible-galaxy`:
```yml
- extracting powerdns.pdns_recursor to [...]/vendor/roles/powerdns.pdns_recursor
 [WARNING]: - powerdns.pdns_recursor was NOT installed successfully: Could not update files in [...]/vendor/roles/powerdns.pdns_recursor: [Errno 95] Operation not supported
````

**Comment by atosatto** [comment]
@strarsis well it really looks like `ansible-galaxy` is not able to write in your `[...]/vendor/` folder.

**Comment by atosatto** [comment]
Closing this issue since it is not related to the `pdns_recursor-ansible` project.
