### ISSUE TITLE
Bug?: No package matching pdns-recursor-4.0.6-1 is available

### ISSUE THREAD

**Issue by eegilbert** [PowerDNS/pdns_recursor-ansible#32]
Hello,

The remote machine I'm connecting to is Ubuntu 17.10 and it's default is python 3. I've had good luck with PDNS Auth server ansible code when setting this in my ansible hosts file:

    [dns]
    10.1.0.10

    [dns:vars]
    ansible_python_interpreter=/usr/bin/python3

However when using the pdns-recursor ansible code I get the message: No package matching pdns-recursor-4.0.6-1 is available

The full trace from an ansible-playbook with -vvv is:

    The full traceback is:
    File "/tmp/ansible_w39r5a9e/ansible_module_apt.py", line 333, in package_status
    pkg = cache[pkgname]
    File "/usr/lib/python3/dist-packages/apt/cache.py", line 200, in __getitem__
    raise KeyError('The cache has no package named %r' % key)

    fatal: [10.1.0.10]: FAILED! => {
        "changed": false, 
        "failed": true, 
        "invocation": {
            "module_args": {
                "allow_unauthenticated": false, 
                "autoclean": false, 
                "autoremove": false, 
                "cache_valid_time": 0, 
                "deb": null, 
                "default_release": null, 
                "dpkg_options": "force-confdef,force-confold", 
                "force": false, 
                "force_apt_get": false, 
                "install_recommends": null, 
                "name": "pdns-recursor-4.0.6-1\n", 
                "only_upgrade": false, 
                "package": [
                    "pdns-recursor-4.0.6-1\n"
                ], 
                "purge": false, 
                "state": "present", 
                "update_cache": null, 
                "upgrade": null
            }
        }, 
        "msg": "No package matching 'pdns-recursor-4.0.6-1\n' is available"
    }

I'm also attaching the fill output of the verbose run

It looks like the version is getting concat to the package name, however I'm not a python guru:

    root@host:/etc/powerdns# apt search pdns-recursor
    Sorting... Done
    Full Text Search... Done
    pdns-recursor/artful,now 4.0.6-1 amd64 [installed]
    PowerDNS Recursor

[pdns_recursor_ansible_error.txt](https://github.com/PowerDNS/pdns_recursor-ansible/files/1436037/pdns_recursor_ansible_error.txt)

Edit: Updated formatting for readability

**Comment by pieterlexis** [comment]
I believe #30 will fix this

**Comment by eegilbert** [comment]
Thanks @pieterlexis I'll close this then.
