### ISSUE TITLE
pdns recursor configuration no longer created

### ISSUE THREAD

**Issue by awhite-telstra** [PowerDNS/pdns_recursor-ansible#36]
It looks like commit 97f5f17 doesn't include configuration.yml and discards pdns_rec_config

**Comment by atosatto** [comment]
@awhite-telstra have you had any chance to test whether you still have issues with the any more recent release of the role?

**Comment by awhite-telstra** [comment]
@atosatto I'm no longer in a job where I'm using this role, so I don't know. Sorry I can't be more help.
