### ISSUE TITLE
recursor.conf.j2 template converts threads to 'yes' if set to '1'

### ISSUE THREAD

**Issue by splk3** [PowerDNS/pdns_recursor-ansible#40]
when setting the `threads` variable to use ansible facts to detect the appropriate number of threads for pdns to use, the `recursor.conf.j2` template will replace '1' with 'yes' if the system only has 1 vcpu.  This does not occur with 2+ vcpus.

`threads` should be a special case and called out in the template before the rest of the true/false boolean conversions to avoid this issue.  I will submit a pull request that includes an example way of fixing this issue.

**Comment by atosatto** [comment]
Thanks @splk3
