### ISSUE TITLE
recursor won't start if forward-zone is set

### ISSUE THREAD

**Issue by celevra** [PowerDNS/pdns_recursor-ansible#5]
Hi,

i'm not sure if this is the right repo because i don't know what ansible means (either google translate).
i can't get the logging to work probably, i'm on 4.0.0~alpha1-1pdns.trusty
if i use the standard config, and change the allow-from, listen and forward-zone powerdns recursor wont start.
if i put the forward options into the forward-zone-file, the recursor will die if i try to resolv a host in that zone.

is there anything i can provide?

regards

celevra

**Comment by pieterlexis** [comment]
Hi celevra, `forward-zones` is indeed broken in the 4.0.0-alpha1 recursor. You can grab the master packages from [the repositories](http://repo.powerdns.com), these contain the fix for this.

**Comment by celevra** [comment]
thank you for the fast answer and clearifying
