### ISSUE TITLE
pdns-rec won't start with changes from PR#56

### ISSUE THREAD

**Issue by kokel** [PowerDNS/pdns_recursor-ansible#58]
Hi,
we use your ansible playbooks and after the last run our pdns-recursor daemons didn't start again.
We are using version 4.2.x and the Problem is the systemd override introduced in PR #56 

We have workaround the problem and have set our own ```pdns_rec_service_overrides``` variable.
But I think the current default breaks all versions < 4.3.

**Comment by kokel** [comment]
Any updates on this?

**Comment by pieterlexis** [comment]
> Any updates on this?

we did not have time to look at this, but indeed the override breaks older versions, patches are welcome.
