### ISSUE TITLE
 Unable to set supplementary groups: Operation not permitted

### ISSUE THREAD

**Issue by lotusnoir** [PowerDNS/pdns_recursor-ansible#59]
hello
I've just installed pdns and now pdns_recursor but when i lunch it with default playbook option i always get

```
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Inserting rfc 1918 private space zones
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Listening for UDP queries on 127.0.0.1:5301
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Enabled TCP data-ready filter for (slight) DoS protection
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Listening for TCP queries on 127.0.0.1:5301
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Set effective group id to 113
Jun  5 08:10:20 dnstest-01.prod.kosc.net pdns_recursor[117644]: Unable to set supplementary groups: Operation not permitted
Jun  5 08:10:20 dnstest-01.prod.kosc.net systemd[1]: pdns-recursor.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 08:10:20 dnstest-01.prod.kosc.net systemd[1]: pdns-recursor.service: Failed with result 'exit-code'.
Jun  5 08:10:20 dnstest-01.prod.kosc.net systemd[1]: Failed to start PowerDNS Recursor
```
if i run the execstart without systemd it works

```
Listening for UDP queries on 127.0.0.1:5301
Enabled TCP data-ready filter for (slight) DoS protection
Listening for TCP queries on 127.0.0.1:5301
Raised soft limit on number of filedescriptors to 4121 to match max-mthreads and threads settings
Set effective group id to 113
Set effective user id to 108
Launching 3 threads
Done priming cache with root hints
Done priming cache with root hints
```
Didnt find how to make it works, please help :)
(running on debian 10)
Thanks in advance

**Comment by pieterlexis** [comment]
This error smells like you're starting pdns_recursor as the user from the service file (`pdns`), but have the `pdns_rec_group` variable set to something else.

**Comment by lotusnoir** [comment]
hello pieterlexis thanks for your support
I've just restart from a fresh install installing **pdns-ansible** role first then  **pdns_recursor-ansible** setting `pdns_rec_group` in vars to `pdns` but the issue keep the same.

**Comment by pieterlexis** [comment]
Please show all your configuration, variables, software versions etc.

**Comment by lotusnoir** [comment]
looks like i found the issue, by default **/etc/systemd/system/pdns-recursor.service.d/override.conf** contains 
```
[Service]
Group=pdns
User=pdns
```
if i delete this content and set `pdns_rec_service_overrides: {}` on vars, the playbook and systemd works

**Comment by pieterlexis** [comment]
A, good to know! You might be running an older PowerDNS Recursor (i.e. not 4.3)?

**Comment by superjcvd** [comment]
Hello same for me: With Debian 10 it seems that the pdns version in official repos is 4.1

+ I can't start the recursor on port 53 because of permissions issues

**Comment by superjcvd** [comment]
Installing the latest version of powerdns with 

pdns_install_repo: "{{ pdns_auth_powerdns_repo_master }}"
pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_master }}" 

solved the problem
