### ISSUE TITLE
install-Linux.yml Set pdns version failing

### ISSUE THREAD

**Issue by felipeneuwald** [PowerDNS/pdns_recursor-ansible#66]
The task _Override the PowerDNS Recursor unit (systemd)_ fails when running the role with `pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_43 }}"` or `pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_master }}"` on Debian Buster because the task _Set pdns version_ fails to set the fact: 

```
TASK [powerdns-recursor : Override the PowerDNS Recursor unit (systemd)] **************************************************************
fatal: [pdns-recursor-001]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ default_pdns_rec_service_overrides }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{  { 'User'  : pdns_rec_user\n    , 'Group' : pdns_rec_group\n    } if _pdns_rec_version is version('4.3', operator='ge')\n      else {}\n}}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: 'LooseVersion' object has no attribute 'version'"}
```

`pdns_rec_ver_output.stderr_lines[0]` is `Oct 01 09:13:27 Asked to run with pdns-distributes-queries set but no distributor threads, raising to 1`, but `Oct 01 09:13:27 PowerDNS Recursor 4.3.4 (C) 2001-2020 PowerDNS.COM BV` was expected. 

Replacing https://github.com/PowerDNS/pdns_recursor-ansible/blob/master/tasks/install-Linux.yml#L41 to `{{ pdns_rec_ver_output.stderr_lines[1]` fixes the issue.

**Comment by pieterlexis** [comment]
This smells like a bug in PowerDNS itself, I'll investigate

**Comment by pieterlexis** [comment]
I've opened https://github.com/PowerDNS/pdns/pull/9569 to fix the issue causing this, I'll try to put a fix in the role as well.
