### ISSUE TITLE
issues using role on Ubuntu 20 instance

### ISSUE THREAD

**Issue by wmclendon** [PowerDNS/pdns_recursor-ansible#69]
good day,

Target host running Ubuntu 20.04, with Ansible control node running 2.10.

ran into two distinct issues -- first an error if Recursor 4.2 is running (which admittedly i'm not clear how that got there) -- the Ansible error is as follows:
```
TASK [powerdns.pdns_recursor : Override the PowerDNS Recursor unit (systemd)] ***********************************************************************
fatal: [pdns-test]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ default_pdns_rec_service_overrides }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{  { 'User'  : pdns_rec_user\n    , 'Group' : pdns_rec_group\n    } if _pdns_rec_version is version('4.3', operator='ge')\n      else {}\n}}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: 'LooseVersion' object has no attribute 'version'"}
```

I believe this is due to the fact `_pdns_rec_version` set is matching regex improperly with the version output below -- it seems to be looking for the first line, and at least somehow on this system the first line was not the version itself:

```
ubuntu@pdns-test:~$ pdns_recursor --version
Oct 31 19:53:55 Asked to run with pdns-distributes-queries set but no distributor threads, raising to 1
Oct 31 19:53:55 PowerDNS Recursor 4.2.1 (C) 2001-2019 PowerDNS.COM BV
Oct 31 19:53:55 Using 64-bits mode. Built using gcc 9.2.1 20200202.
Oct 31 19:53:55 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
...cut for brevity...
```

I was able to resolve the above by uninstalling the older version and re-running the playbook.  then I ran into second issue -- below ansible task failure:

```
TASK [powerdns.pdns_recursor : Restart PowerDNS Recursor] *******************************************************************************************
[WARNING]: Ignoring "sleep" as it is not used in "systemd"
fatal: [pdns-test]: FAILED! => {"changed": false, "msg": "Unable to restart service pdns-recursor: Job for pdns-recursor.service failed because the control process exited with error code.\nSee \"systemctl status pdns-recursor.service\" and \"journalctl -xe\" for details.\n"}
```

In chasing the issue, it was due to Ubuntu 20 systemd-resolve already listening on port 53, and I had to kill that before the playbook would succeed beginning to end with command `sudo systemctl disable --now systemd-resolved`

Thanks,

Will

**Comment by wmclendon** [comment]
a brief update -- it looks like 4.2.1 version is installed from the ubuntu apt repo, since I wasn't originally specifying `pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_44 }}"` in my host_vars file

i uninstalled pdns-recursor 4.2.1, ran the playbook again with the above var specified, and it then failed due to the systemd-resolved as expected.  I manually disabled systemd-resolved again, and re-ran the playbook and it succeeded as expected.  I guess before that step there needs to be a play for systemd-resolved to be disabled and shut off and then restarting pdns-recursor, at least for ubuntu 20 systems.

**Comment by jbe-dw** [comment]
Hello,

This bug is due to a task targeting the wrong line of an output. It's still present in the 1.4.0 release but the tasks have been replaced in the master branch though.

You can either:
- not specifying a role version when pulling from ansible galaxy to get the path (or clone the master branch directly)
- specify `pdns_rec_package_version` in your inventory variables but you would stick to a specific release.
- patch tasks/install-Linux.yml this way (lines 41-42)

```yaml
 38     - name: Set pdns version
 39       set_fact:
 40         _pdns_rec_version: >-
 41           {{ pdns_rec_ver_output.stderr_lines
 42                 | select('search', '(?<=PowerDNS Recursor )[0-9.]+(?= )')
 43                 | regex_search("(?<=PowerDNS Recursor )[0-9.]+(?= )")
 44               if pdns_rec_package_version | length == 0
 45               else pdns_rec_package_version
 46           }}
```

PowerDNS Ansible Team, releasing 1.4.1 quickly with your patch could be a good idea. Using versioning of roles in a Playbook is a good practice as the code would never change.

**Comment by jbe-dw** [comment]
@wmclendon PowerDNS role is not supposed to watch if a port is used on your system, it's your duty to configure it with available ports.

**Comment by wmclendon** [comment]
that's fair, however i think there then becomes a chicken and egg problem whereby the ubuntu system needs DNS resolution working for the role to execute on the system, which it does by default via the systemd-resolved, but then the role fails to complete due to the port conflict.  my career focus has been IP networking, so I'm not much of a linux systems guy so my knowledge is limited here (but working on that...), but I am sure there are some pre-tasks that could and should be done that remove systemd-resolved and instead use some other configuration to ensure dns resolution works via resolv.conf or something like that.  whether that is handled in the role or needs to be done by the operator beforehand i suppose could be debated, or perhaps just mentioned in docs as likely issue to account for on ubuntu systems.

thank you for response, i'll see about making updates to my playbook to account for this port conflict.

**Comment by snesbittsea** [comment]
@wmclendon I don't know your exact situation, but I'm using the following 3 step approach to dealing with the Systemd-Resolved conflict. In a nutshell the steps are _prior to installing powerdns_:

1. Update /etc/systemd/resolved.conf to add the following to set DNS to 127.0.0.1, Domains to the domain you want to resolve and DNSStubListener to no. Here is my resolved.conf:
`# Ansible managed

[Resolve]
DNS=127.0.0.1
Domains=~consul
DNSStubListener=no`

2. reset the /etc/resolv.conf link to the non-stub version. `sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`
3. Bounce systemd-resolved: `sudo systemctl restart systemd-resolved`

FYI, I'm writing this down off the top of my head and without stringent testing. YMMV, but it is working for me.

Ping me if you need help or further clarification.
